chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<str:no_ktp>/', views.show_chat)
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
=======
    re_path('user/', include(('user.urls', 'user'), namespace='user')),
    path('admin/', admin.site.urls),
>>>>>>> 83b575e29aade16d55ef983369ea24d1355d69c2
    path('pengiriman/', include('semogakelar.urls')),
    path('barang/', include('barang.urls')),
    path('chat/', include('chat.urls'))
    ]

user/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('<str:ktp>', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('create/', views.create, name='create'),
    path('daftar/', views.daftar, name='daftar'),
    path('index/', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('update/<str:namaBarang>/', views.update, name='update'),
    path('create_item/', views.post_item_admin, name='createItem'),
    path('update_item/', views.updateItem, name='updateItem'),
    path('check_login/', views.loginCheck, name='checkLogin'),
    path('check_signup/', views.checkSignUp, name='checkSignUp'),
    path('delete/<str:namaBarang>/', views.deleteItem, name='delete')
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db import connection
from .Forms import ItemForm, Login, SignUp, ItemFormUpdate
import psycopg2
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect

response = {}

def profile(request, ktp):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM toy_rent.pengguna where No_ktp = '" + ktp + "'")
        data = cursor.fetchall()
        cursor.close()
    response['user'] = data
    return render(request, 'profile.html', response)

def login(request):
    response['fill_form'] = Login
    return render(request, 'login.html', response)

def create(request):
    response['fill_form'] = ItemForm
    return render(request, 'create.html', response)

def daftar(request):
    response['barang'] = get_all_barang()
    return render(request, 'daftar_item.html', response)

def index(request):
    return render(request, 'index.html', response)

def signup(request):
    response['fill_form'] = SignUp
    return render(request, 'sign up.html', response)

def update(request, namaBarang):
    response['fill_form'] = ItemFormUpdate
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM toy_rent.item")
        data = cursor.fetchall()
        cursor.close()
    response['up'] = data
    return render(request, 'update.html', response)

def get_all_barang():
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM toy_rent.kategori_item")
        data = cursor.fetchall()
        cursor.close()
    print(data)
    return data

@csrf_exempt
def post_item_admin(request):
    if request.method == 'POST':
        print(request.POST)
        saveThisItem = (request.POST['nama'], request.POST['deskripsi'],
                    request.POST['usiaMin'], request.POST['usiaMax'],
                    request.POST['bahan'])
        saveThisKategori = (saveThisItem[0], request.POST['kategori'])
        pg_insert_query_item = """INSERT INTO toy_rent.item(Nama, Deskripsi, Usia_dari, Usia_Sampai, Bahan) VALUES (%s,%s,%s,%s,%s)"""
        pg_insert_query_kategori_item = """INSERT INTO toy_rent.kategori_item(Nama_item, Nama_kategori) VALUES (%s,%s)"""
        with connection.cursor() as cursor:
            cursor.execute(pg_insert_query_item, saveThisItem)
            cursor.execute(pg_insert_query_kategori_item, saveThisKategori)
        return HttpResponseRedirect('/user/daftar')

@csrf_exempt
def loginCheck(request):
    if request.method == 'POST':
        checkThis = request.POST['ktp']
        with connection.cursor() as cursor:
            pg_insert_query_user = "SELECT * FROM toy_rent.pengguna where No_ktp = '" + checkThis + "'"
            cursor.execute(pg_insert_query_user)
            data = cursor.fetchall()
            cursor.close()
        print(data)
        if (len(data) > 0):
            return HttpResponseRedirect('/user/daftar')
        else:
            return HttpResponseRedirect('/user/login')

def checkSignUp(request):
    ktp = request.POST['ktp']
    signThis = (request.POST['ktp'], request.POST['nama'], request.POST['email'], request.POST['tanggalLahir'], request.POST['telepon'])
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM toy_rent.pengguna where No_ktp = '" + ktp + "'")
        data = cursor.fetchall()
        cursor.close()
    if (len(data) == 0):
        pg_insert_query_pengguna = """INSERT INTO toy_rent.pengguna(No_ktp, Nama_lengkap, Email, Tanggal_lahir, No_telp) VALUES (%s,%s,%s,%s,%s)"""
        with connection.cursor() as cursor:
            cursor.execute(pg_insert_query_pengguna, signThis)
        return HttpResponseRedirect('/user/daftar')
    else:
        return HttpResponseRedirect('/user/login')

def deleteItem(request, namaBarang):
    with connection.cursor() as cursor:
        cursor.execute("DELETE from toy_rent.kategori_item where nama_item= '" + namaBarang + "'")
        cursor.execute("DELETE from toy_rent.item where nama= '" + namaBarang + "'")
        cursor.close()
    return HttpResponseRedirect("/user/daftar")

@csrf_exempt
def updateItem(request):
    updateThisItem = (request.POST['deskripsi'],
                    request.POST['usiaMin'], request.POST['usiaMax'],
                    request.POST['bahan'])
    pg_update_query_item = """UPDATE toy_rent.item set deskripsi = %s , usia_dari = %s , usia_sampai = %s , bahan = %s"""
    with connection.cursor() as cursor:
        cursor.execute(pg_update_query_item, updateThisItem)
    return HttpResponseRedirect("/user/daftar/")

user/templates/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Toysrent</title>
    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="LayoutIt!">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
  </head>
<body>
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="navbar-toggler-icon"></span>
				</button> <a class="navbar-brand" href="#">ToysRent</a>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="navbar-nav">
						<li class="nav-item">
							 <a class="nav-link" href="#">Link</a>
						</li>
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								 <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>
					</ul>
					<form class="form-inline">
						<input class="form-control mr-sm-2" type="text" />
						<button class="btn btn-primary my-2 my-sm-0" type="submit">
							Search
						</button>
					</form>
					<ul class="navbar-nav ml-md-auto">
						<li class="nav-item active">
							 <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
								 <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	{% block content %}
	{% endblock %}
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
</body>
</html>

user/templates/create.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
		<form action="{% url 'user:createItem' %}" method="POST">
			{% csrf_token %}
			{{ fill_form }}
			<button type="submit" class="btn btn-success" formmethod="post">Submit</button>
		</form>
		</div>
		<div class="col-md-1">
		</div>
	</div>
{% endblock %}

user/templates/daftar_item.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<h3 class="text-center">Daftar Item</h3>
			<table class="table">
				<thead>
					<tr>
						<th>Nama Item</th>
						<th>Kategori</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					{% for b in barang %}
					<tr>
						<td>{{ b.0 }}</td>
						<td>{{ b.1 }}</td>
						<td>
							<form action="{% url 'user:update' b.0 %}">
								<button type="submit" class="btn btn-success">Update</button>
							</form>
							<form action="{% url 'user:delete' b.0 %}">
								<button type="submit" class="btn btn-danger">Delete</button>
							</form>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-md-1">
		</div>
	</div>
{% endblock %}

user/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<h3>
				FORM LOGIN
			</h3>
			<form role="form">
				<div class="form-group">
					<label for="exampleInputEmail1">
						Nomor KTP
					</label>
					<input type="text" class="form-control" id="exampleInputEmail1">
				</div>
				<div class="form-group">
					 
					<label for="exampleInputPassword1">
						email
					</label>
					<input type="email" class="form-control" id="exampleInputPassword1">
				</div>
				<button type="submit" class="btn btn-primary">
					Submit
				</button>
			</form>
		</div>
		<div class="col-md-1">
		</div>
	</div>
{% endblock %}

user/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<h3>
				FORM LOGIN PENGGUNA
			</h3>
			<form action="{% url 'user:checkLogin' %}" method="POST">
			{% csrf_token %}
			{{ fill_form }}
			<button type="submit" class="btn btn-success" formmethod="post">Submit</button>
		</form>
		</div>
		<div class="col-md-1">
		</div>
	</div>
{% endblock %}

user/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-1">
			<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg" class="rounded-circle" />
		</div>
		<div class="col-md-9">
			<h3 class="text-center">
				{{ user.0.1 }}
			</h3>
		</div>
		<div class="col-md-1">
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<br>
			<br>
			<dl>
				<dt>
					Nama Lengkap:
				</dt>
				<dd>
					{{ user.0.1 }}
				</dd>
				<dt>
					Email: 
				</dt>
				<dd>
					{{ user.0.2 }}
				</dd>
				<dt>
					Tanggal lahir:
				</dt>
				<dd>
					{{ user.0.3 }}
				</dd>
				<dt>
					Nomor telepon:
				</dt>
				<dd>
					{{ user.0.4 }}
				</dd>
			</dl>
		</div>
		<div class="col-md-1">
		</div>
	</div>
{% endblock %}

user/templates/sign up.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<h3>
				FORM PENDAFTARAN PENGGUNA
			</h3>
			<form action="{% url 'user:checkSignUp' %}" method="POST">
			{% csrf_token %}
			{{ fill_form }}
			<button type="submit" class="btn btn-success" formmethod="post">Submit</button>
			</form>
		</div>
		<div class="col-md-1">
		</div>
	</div>
{% endblock %}

user/templates/update.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<p>Nama sekarang: {{up.0.0}}</p>
			<p>Deskripsi: {{up.0.1}}</p>
			<p>Usia Minimal: {{up.0.2}}</p>
			<p>Usia Maksimal: {{up.0.3}}</p>
			<p>Bahan: {{up.0.4}}</p>
		<form action="{% url 'user:updateItem' %}" method="POST">
			{% csrf_token %}
			{{ fill_form }}
			<button type="submit" class="btn btn-success" formmethod="post">Submit</button>
		</form>
		</div>
		<div class="col-md-1">
		</div>
	</div>
{% endblock %}